// Client-side form validation for static export
import { z } from "zod";

const SummarizeSchema = z.object({
  document: z.string().min(50, "Document text must be at least 50 characters long."),
});

export type FormState = {
  message: string;
  summary?: string;
  errors?: {
    document?: string[];
  };
};

// Client-side form handler for static hosting
export function validateCaseStudyForm(formData: {
  document: string;
}): FormState {
  const validatedFields = SummarizeSchema.safeParse(formData);

  if (!validatedFields.success) {
    return {
      message: "Validation failed. Please check your input.",
      errors: validatedFields.error.flatten().fieldErrors,
    };
  }

  // For static hosting, you would typically:
  // 1. Use an external API service
  // 2. Send data to a serverless function
  // 3. Use a third-party AI service API
  
  try {
    // Simulate AI processing - in a real app, you'd call an external API
    const mockSummary = generateMockSummary(validatedFields.data.document);
    
    return { 
      message: "Summary generated successfully!", 
      summary: mockSummary 
    };
  } catch (error) {
    console.error("Error generating summary:", error);
    return { 
      message: "Error: An unexpected error occurred while generating the summary." 
    };
  }
}

// Mock summary generator for demo purposes
function generateMockSummary(document: string): string {
  const wordCount = document.split(' ').length;
  const sentences = document.split('.').filter(s => s.trim().length > 0);
  const firstSentence = sentences[0]?.trim() + '.';
  
  return `**Executive Summary**

This document contains approximately ${wordCount} words and covers key business insights. 

**Key Points:**
• ${firstSentence}
• The document discusses strategic initiatives and market opportunities
• Implementation recommendations are provided for stakeholder consideration
• ROI projections and risk assessments are included in the analysis

**Conclusion:**
This case study provides valuable insights for decision-making and strategic planning. The analysis suggests positive outcomes with proper implementation of the recommended strategies.

*Note: This is a demo summary. In production, this would be generated by an actual AI service.*`;
}
